lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pouya Kary
url:              https://kary.us
paginate:         1
baseurl:          /
